//
//  DetailVIPInteractor.swift
//  FlawlessNavigation
//
//  Created by Radim Halfar on 05.04.18.
//  Copyright (c) 2018 Inloop. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailVIPBusinessLogic {
    func getData()
}

final class DetailVIPInteractor: DetailVIPBusinessLogic {
    var presenter: DetailVIPPresentationLogic?
    var item: InloopContact?
    
    func getData() {
        
    }
}
